"""Run the whole JSON save/load attack suite, sequentially (2 cores only).

    python3 run_all.py            # everything
    python3 run_all.py t03 t07    # just those

Fixtures for the legacy tests are regenerated by t05_gen_legacy.py; run it
before t06/t07 if fixtures/ is empty.
"""
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ORDER = ["t00_smoke.py", "t01_fixes.py", "t02_badge.py", "t03_races.py",
         "t03b_crossfile.py", "t04_errors.py", "t05_gen_legacy.py",
         "t06_legacy_load.py", "t07_adopt_defaults.py", "t07d_prev30_render.py",
         "t08_payload.py", "t09_nonfs_reload.py", "t10_misc.py", "t11_twotabs.py",
         "t12_newcode.py", "t13_round3.py", "t14_recheck.py",
         "t14b_probe.py", "t15_round4.py", "t15b_probe.py", "t15c_probe.py",
         "t15d_reconcile.py", "t15e_timing.py", "t15f_restamp.py", "t15g_exact.py",
         "t16_round5.py", "t16g_fair.py", "probe_stale.py", "probe_stale2.py"]

want = sys.argv[1:]
fails = 0
for name in ORDER:
    if want and not any(w in name for w in want):
        continue
    print("\n########## " + name + " ##########", flush=True)
    r = subprocess.run([sys.executable, "-u", str(HERE / name)], cwd=str(HERE))
    if r.returncode:
        fails += 1
        print("!! %s exited %d" % (name, r.returncode))
print("\ndone — %d script(s) errored" % fails)
